'''
    Created by Eric

    store configure values for the FMC program
'''

SERVER_IP = "127.0.0.1"
VIDEO_PORT = 1140
DATA_PORT = 1910
CMD_PORT = 4470

CMD_MAX_RECV = 1024

CMD_PACK_FORMAT = ""
CMD_PACK_KEYS = []

DATA_PACK_FORMAT = ""

VIDEO_QUALITY = 10
VIDEO_DEVICE = 0
VIDEO_CRATE = 100
VIDEO_DELAY = 0.1